### ISSUE TITLE
Not working with new media id's

### ISSUE THREAD

**Issue by manojbojja** [slang800/instagram-id-to-url-segment#1]
1245771331041990029_23537020 test this

error BigNumber Error: new BigNumber() not a number: 1245771331041990029_23537020

**Comment by notslang** [comment]
`1245771331041990029_23537020` is actually 2 ids. The first part (`1245771331041990029`) is the post, and we can convert that into a URL segment by doing `instagramIdToUrlSegment('1245771331041990029')`, which gives us [`BFJ3mzaH5WN`](https://www.instagram.com/p/BFJ3mzaH5WN/).

The second part (`23537020`) is the user. I'm not sure if that number has any significance... It's probably just a separate identifier so people can change their username without needing to update all the posts in the db belonging to that user or something.

Read this post for a full explanation: http://carrot.is/coding/instagram-ids

AFAIK, Instagram has not changed their ID format in the last couple years, so Imma close this up. Be sure to comment if you have any other questions or if I made a mistake.
